name: Wakatime Charts

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0-23/1 * * *'

jobs:
  update-charts:
    name: Update stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          API_BASE_URL: https://wakatime.com/api
          SHOW_TITLE: true
          SECTION_NAME: waka
          BLOCKS: ->
          CODE_LANG: all_time 
          TIME_RANGE: true
          LANG_COUNT: 10
          SHOW_TIME: true
          SHOW_TOTAL: true
          SHOW_MASKED_TIME: true
          STOP_AT_OTHER: true